//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gramps.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gramps.Core.Resources.StaticValues", typeof(StaticValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indexedControl.
        /// </summary>
        public static string Class_indexedControl {
            get {
                return ResourceManager.GetString("Class_indexedControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not reply to this email. It was automatically generated..
        /// </summary>
        public static string EmailAutomatedDisclaimer {
            get {
                return ResourceManager.GetString("EmailAutomatedDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new proposal:.
        /// </summary>
        public static string EmailCreateProposal {
            get {
                return ResourceManager.GetString("EmailCreateProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Filter_Active {
            get {
                return ResourceManager.GetString("Filter_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActive.
        /// </summary>
        public static string Filter_Not_Active {
            get {
                return ResourceManager.GetString("Filter_Not_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent out to list for proposals.
        /// </summary>
        public static string InitialCall {
            get {
                return ResourceManager.GetString("InitialCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Created Successfully..
        /// </summary>
        public static string Message_CreatedSuccessfully {
            get {
                return ResourceManager.GetString("Message_CreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Edited Successfully..
        /// </summary>
        public static string Message_EditedSuccessfully {
            get {
                return ResourceManager.GetString("Message_EditedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to {0}..
        /// </summary>
        public static string Message_NoAccess {
            get {
                return ResourceManager.GetString("Message_NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found..
        /// </summary>
        public static string Message_NotFound {
            get {
                return ResourceManager.GetString("Message_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem selecting {0}..
        /// </summary>
        public static string Message_ProblemSelecting {
            get {
                return ResourceManager.GetString("Message_ProblemSelecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Removed Successfully..
        /// </summary>
        public static string Message_RemovedSuccessfully {
            get {
                return ResourceManager.GetString("Message_RemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add {0}.
        /// </summary>
        public static string Message_UnableToAdd {
            get {
                return ResourceManager.GetString("Message_UnableToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent out to applicant if proposal is approved.
        /// </summary>
        public static string ProposalApproved {
            get {
                return ResourceManager.GetString("ProposalApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent out to applicant to confirm proposal has been created.
        /// </summary>
        public static string ProposalConfirmation {
            get {
                return ResourceManager.GetString("ProposalConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent out to applicant to notify them that their proposal has not been accepted.
        /// </summary>
        public static string ProposalDenied {
            get {
                return ResourceManager.GetString("ProposalDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent to applicant to inform them their proposal has been set back to edit.
        /// </summary>
        public static string ProposalUnsubmitted {
            get {
                return ResourceManager.GetString("ProposalUnsubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string RB_Decission_Approved {
            get {
                return ResourceManager.GetString("RB_Decission_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        public static string RB_Decission_Denied {
            get {
                return ResourceManager.GetString("RB_Decission_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotDecided.
        /// </summary>
        public static string RB_Decission_NotDecided {
            get {
                return ResourceManager.GetString("RB_Decission_NotDecided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notified.
        /// </summary>
        public static string RB_Notified_Notified {
            get {
                return ResourceManager.GetString("RB_Notified_Notified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotNotified.
        /// </summary>
        public static string RB_Notified_NotNotified {
            get {
                return ResourceManager.GetString("RB_Notified_NotNotified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveWithoutValidation.
        /// </summary>
        public static string RB_SaveOptions_SaveNoValidate {
            get {
                return ResourceManager.GetString("RB_SaveOptions_SaveNoValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveAndValidate.
        /// </summary>
        public static string RB_SaveOptions_SaveWithValidation {
            get {
                return ResourceManager.GetString("RB_SaveOptions_SaveWithValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitFinal.
        /// </summary>
        public static string RB_SaveOptions_SubmitFinal {
            get {
                return ResourceManager.GetString("RB_SaveOptions_SubmitFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotSubmitted.
        /// </summary>
        public static string RB_Submitted_NotSubmitted {
            get {
                return ResourceManager.GetString("RB_Submitted_NotSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string RB_Submitted_Submitted {
            get {
                return ResourceManager.GetString("RB_Submitted_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotWarned.
        /// </summary>
        public static string RB_Warned_NotWarned {
            get {
                return ResourceManager.GetString("RB_Warned_NotWarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warned.
        /// </summary>
        public static string RB_Warned_Warned {
            get {
                return ResourceManager.GetString("RB_Warned_Warned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent out to list of reviewers to notify them that the proposals are ready to be reviewed.
        /// </summary>
        public static string ReadyForReview {
            get {
                return ResourceManager.GetString("ReadyForReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent out to list applicants that have not finilized their proposals.
        /// </summary>
        public static string ReminderCallIsAboutToClose {
            get {
                return ResourceManager.GetString("ReminderCallIsAboutToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Report_Approved {
            get {
                return ResourceManager.GetString("Report_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AwardAmount.
        /// </summary>
        public static string Report_AwardedAmount {
            get {
                return ResourceManager.GetString("Report_AwardedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Report_Comments {
            get {
                return ResourceManager.GetString("Report_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        public static string Report_Denied {
            get {
                return ResourceManager.GetString("Report_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigators.
        /// </summary>
        public static string Report_Investigators {
            get {
                return ResourceManager.GetString("Report_Investigators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmountRequested.
        /// </summary>
        public static string Report_RequestedAmount {
            get {
                return ResourceManager.GetString("Report_RequestedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProposalSequence.
        /// </summary>
        public static string Report_Sequence {
            get {
                return ResourceManager.GetString("Report_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string Report_Submitted {
            get {
                return ResourceManager.GetString("Report_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApprovedAmount.
        /// </summary>
        public static string TokenApprovedAmount {
            get {
                return ResourceManager.GetString("TokenApprovedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseDate.
        /// </summary>
        public static string TokenCloseDate {
            get {
                return ResourceManager.GetString("TokenCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateProposalLink.
        /// </summary>
        public static string TokenCreateProposalLink {
            get {
                return ResourceManager.GetString("TokenCreateProposalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProposalLink.
        /// </summary>
        public static string TokenProposalLink {
            get {
                return ResourceManager.GetString("TokenProposalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProposalMaximum.
        /// </summary>
        public static string TokenProposalMaximum {
            get {
                return ResourceManager.GetString("TokenProposalMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReviewerName.
        /// </summary>
        public static string TokenReviewerName {
            get {
                return ResourceManager.GetString("TokenReviewerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VersionKey.
        /// </summary>
        public static string VersionKey {
            get {
                return ResourceManager.GetString("VersionKey", resourceCulture);
            }
        }
    }
}
