ALTER TABLE [dbo].[QuestionsXValidators]
    ADD CONSTRAINT [PK_QuestionXValidator] PRIMARY KEY CLUSTERED ([QuestionsId] ASC, [ValidatorsId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

